version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: law4minor_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: law4minor
    ports:
      - "5550:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
